---
title: "TZM-bl infection assay 004 28April16"
author: "Claire Levy"
date: "April 28, 2016"
output: html_document
---
## Experiment goal

Measure effect of pre-incubating TZM-bl cells and SE before adding virus (either JR-FL or Bal) and compared when the SE are removed ("Washed") or left on the cells ("Unwashed")before adding the virus.

* Used day8 purified virus for Bal and JR-FL (in exp 003 used d5 for JR-FL)

## Results

Except for JR-FL washed, there is a dose response effect of the SE for both Bal and JR-FL; the RLU is lower (less infection) as the concentration of SE per PFU increases. All replicates were at least 3x the cells only (no virus, no SE) control. 

Bal: In general, the RLU is lower (less infection) for the cells that were washed.

JR-FL: The RLU is lower for the washed cells in the 10^4 and 10^6 exos per PFU conditions, but higher/the same for the 10^5 exos per PFU condition. Also note that the virus alone control is lower than expected.

```{r, echo=FALSE,warning=FALSE, message= FALSE}
  
library(plateR)
library(ggplot2)
library(dplyr)
library(stringr)
library(scales)

setwd("J:/MacLabUsers/HLADIK SHARED/Projects/Exosomes/TZM-bl_infection_assays/TZM-bl_infection_assay_004")

#read in the results and metadata
dat<-read_plate("plateR_formatted_metadata_and_results.csv")

#make factors in a good order for plotting
dat$Condition<-factor(dat$Condition)

dat$Condition <-factor(dat$Condition,levels(dat$Condition)[c(8,7,15,1:6,9:14)])
                       


#add columns to better define the conidtions
dat<-dat %>%
  mutate(Virus = ifelse(str_detect(Condition, "[B*]")== TRUE,"Bal",
         ifelse(str_detect(Condition,"[J*]")==TRUE,"JR-FL", "No_Virus")))%>%
  mutate(SE_Conc = ifelse(str_detect(Condition, "4")== TRUE,"10^4",
         ifelse(str_detect(Condition,"5")==TRUE,"10^5",
                ifelse(str_detect(Condition,"6")==TRUE,
                       "10^6","No_SE")
         )
  )
  )

#add a column for washed and unwashed
dat<-dat %>%
  mutate(Wash = ifelse(str_detect(Condition, "W")== TRUE,"Washed","Unwashed"))


#make the Condition column even more understandable.
dat<-dat %>%
  mutate(SE_Conc = ifelse(Condition == "Bal"|Condition == "JR-FL","No_SE", SE_Conc))%>%
  mutate(SE_Conc = ifelse(Condition == "Cells_only","No_virus_No_SE", SE_Conc))



#make factors in a good order for plotting
dat$SE_Conc<-factor(dat$SE_Conc)

dat$SE_Conc <-factor(dat$SE_Conc,levels(dat$SE_Conc)[c(5,4,1:3)])
                       



# split the data up into different dfs for each virus and keep the controls there too.

datBal <-dat %>%
  filter(Virus == "Bal" | Virus == "No_Virus")


datJRFL<-dat%>%
  filter(Virus == "JR-FL" | Virus == "No_Virus")

#all the Bal data
#outlier: B_CSE_10^6_N :A03 is really high
ggplot(datBal,aes(x = SE_Conc, y = RLU))+ scale_y_continuous(labels = scientific)+
  geom_point(aes(color = Wash), size = 3)+
  #facet_wrap(~Wash, scales = "free_x")+
  ggtitle("Bal data: all reps are 3x cells only control")



#all the JRFL data
#outliers: J_CSE_10^5_W: D11 is much higher

ggplot(datJRFL,aes(x = SE_Conc, y = RLU))+
  scale_y_continuous(labels = scientific)+
  geom_point(aes(color = Wash), size = 3)+
  ggtitle("JR-FL: all reps are 3x cells only control")



#determine the average concentration of the cells alone
avgCellsOnly<-dat %>%
  filter(SE_Conc =="No_virus_No_SE" ) %>%
  group_by(Condition)%>%
  summarise(avgRLU = mean(RLU))


#make a df that just includes RLU that are 3x the "cells only" condition, plus the controls

datBal3xCntl<-datBal %>%
  filter(RLU >= 3*avgCellsOnly$avgRLU |Condition == "Cells_only")


datJRFL3xCntl<-datJRFL %>%
  filter(RLU >= 3*avgCellsOnly$avgRLU |Condition == "Cells_only")#all are 3x cells only avg

#all JRFL and Bal data were at least 3x cells only





#together
#first remove the no virus condition
# minusNoVirus<-dat %>%
#   filter(Virus != "No_Virus")
# 
# ggplot(minusNoVirus,aes(x = SE_Conc, y = RLU))+
#   scale_y_continuous(labels = scientific)+
#   geom_point(aes(color = Wash), size = 4)+
#   ggtitle("All reps are 3x cells only control")+
#   facet_wrap(~Virus)

```


